// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkOBoH3TMNjegVqMczwwidVITbynP6S9s',
    appId: '1:571520311147:android:0aac7bbdf8a0d3c7feb62e',
    messagingSenderId: '571520311147',
    projectId: 'notification-flutter-30d1a',
    storageBucket: 'notification-flutter-30d1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-NRiKKz0ofRYDxc51148UYwMqma2e4Yk',
    appId: '1:571520311147:ios:4566a4891fb027d7feb62e',
    messagingSenderId: '571520311147',
    projectId: 'notification-flutter-30d1a',
    storageBucket: 'notification-flutter-30d1a.appspot.com',
    iosBundleId: 'com.example.notificationFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-NRiKKz0ofRYDxc51148UYwMqma2e4Yk',
    appId: '1:571520311147:ios:4566a4891fb027d7feb62e',
    messagingSenderId: '571520311147',
    projectId: 'notification-flutter-30d1a',
    storageBucket: 'notification-flutter-30d1a.appspot.com',
    iosBundleId: 'com.example.notificationFlutter',
  );

}